name: Deploy to GitHub

on:
  workflow_run:
    workflows: ["Gradle Build and Test"]
    types:
      - completed

jobs:
  deploy:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Download success marker
      uses: actions/download-artifact@v2
      with:
        name: success-marker
        path: .

    - name: Check for success marker
      run: |
        if [ ! -f success.txt ]; then
          echo "Success marker not found, exiting."
          exit 1
        fi

    - name: Push changes to GitHub
      run: |
        git add .
        git commit -m "Automated commit by GitHub Actions"
        git push origin dev
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
